config/routes.rb
Blog::Application.routes.draw do

  resources :posts do
    resources :comments
    resources :products
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :commenter
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :important

  validates :title, :content, :presence => true
  validates :title, :length => { :minimum => 2 }
  validates :title, :uniqueness => true

  has_many :comments, :dependent => :destroy
  has_many :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :post
  attr_accessible :name, :price, :released
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_resource, only: [:show, :update, :destroy, :edit]

  def set_resource
    raiser "you must overwrite this method in your controller!"
  end

  protected

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = @resource.comments.create(params[:comment])
    redirect_to post_path(@resource)
  end

  def destroy
    @comment = @resource.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@resource)
  end

  def set_resource
    @resource ||= Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #regarder dans application_controller (part 5 method au comemence de l app)
   before_filter :set_posts, only: [:index]

  def index
  end


  def show
  end

  def new
    @resource = Post.new
  end


  def update
    if @resource.update_attributes(params[:post])
      redirect_to(posts_path, :notice => "Post was success updated")
    else
       render :action => "edit"
    end
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
      redirect_to posts_path, :notice => "Your post was saved"
    else
      render "new"
    end
  end

  def edit
  end

  def destroy
    @resource.destroy
    redirect_to posts_url
  end

  protected

  def set_resource
    @resource ||= Post.find(params[:id])
  end

  def set_posts
    @posts ||=  Post.all
    if params[:important].present?
      @posts = Post.where(important: (params[:important] == 'true'))
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @products = Product.order(sort_column + " " + sort_direction)
  end

  def show
    @product
  end

  def new
    @products = Product.new
  end

  def create
    @products = Products.new(params[:product])
    if @products.save
      redirect_to post_products_path(:post_id), :notice => "Your post was saved"
    else
      render "new"
    end
  end

  protected

  def set_resource
    @resource ||= Post.find(params[:post_id])
  end

  def set_product
    @product ||= Product.all
  end

  private

  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == params[:sort] && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comments/_comments.html.haml
-@resource.comments.each do |comment|
  = comment.commenter
  = comment.body

app/views/comments/_form.html.haml
= form_for([@resource, @resource.comments.build]) do |f|
  %p
  = f.label :commenter
  = f.text_field :commenter
  %p
  = f.label :body
  %p
  = f.text_area :body
  %p
  = f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/posts/_form.html.haml
= form_for @resource do |f|
  %p
    = f.label :title
    %br/
    = f.text_field :title
  %p
    = f.label :content
    %br/
    = f.text_field :content
  %p
    = f.label :important
    %br/
    = f.check_box :important
  %p
    = f.submit "Update Post"

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "back", posts_path

app/views/posts/index.html.haml
%h1 Welcome to my OP blog

= link_to 'Important', posts_path(:important => 'true')
= link_to 'Not Important', posts_path(:important => 'false')
= link_to 'All', posts_path

%table.styled

  - @posts.each do |post|
    %tr
      %td= link_to post.title, post_path(post)
      %td{style: (post.important? ? 'color: red ' : nil)}= post.content
      %td= post.important?
      %td= link_to "Update", edit_post_path(post)
      %td= link_to "Delete", post, :confirm => "Are you sure", :method => :delete
%hr
= link_to "New", new_post_path
%br/
= link_to "Products", post_products_path(:post_id)

app/views/posts/new.html.haml
%h1 Create a new post

= render 'form'

= link_to "Back", posts_path

app/views/posts/show.html.haml
%h1= @resource.title
%p= @resource.content
%br/
%br/
= @resource.created_at
%br/
%hr
%h2 Comments :
%br/
- @resource.comments.each do |comment|
  = comment.commenter
  = comment.body
  = link_to 'Destroy Comment', [comment.post, comment],
   :confirm => 'Are you sure Ginette',
   :method => :delete
  %br/


%h3 "Add a Comment"
= render 'comments/form'

%hr
= link_to "Edit", edit_post_path(@resource)
%hr
= link_to "back", posts_path

app/views/products/index.html.haml
%h1 Products

%table.styled
  %tr
    %th
      = sortable "Name"
      = sortable "Price"
      = sortable "Released"
  - for p in @products
    %tr
      %td
        = p.name
        = p.price
        = p.released

%hr
%h3 Create a new Products
= link_to "New Products", new_post_product_path
%br/
%br/
= link_to "Post", posts_path

app/views/products/new.html.haml
= form_for @products do |p|
  %p
    = p.label :name
    %br/
    = p.text_field :name
  %p
    = p.label :price
    %br/
    = p.text_field :price
  %p
    = p.label :released
    %br/
    = p.text_field :released
  %p
    = p.submit "Create"

app/views/products/show.html.haml
%h1 Hello there